### ISSUE TITLE
Creating a Rock paper Scissor games using javascript

### ISSUE THREAD

**Issue by Sri-vishnu-r1431** [Learn-Write-Repeat/Hacktoberfest-Contribution#6]
The aim is to create an Rock Paper Scissor game using JS-DOM

**Comment by ashutoshkrris** [comment]
Alright @Sri-vishnu-r1431 
Go for it!

**Comment by SurendarSingh** [comment]
Ok, So I need to provide HTML, CSS, JS - 3 different files?
or is there any predefined file in which I can edit the code?

**Comment by Sri-vishnu-r1431** [comment]
I dont know about may be I can put all in one single file?
or create three files?
@SurendarSingh

**Comment by ashutoshkrris** [comment]
You need to create a folder with your project name within the contributions folder. Make sure you follow the naming convention as mentioned in README
Inside your project folder, create a README file describing your project.
Additionally, you can create separate HTML, CSS and JS files or just create one index.html and put everything inside that.
Kindly go through the README to understand better. You can also view other contributions, how they have done.

Also, do let me know who is working on this issue so that I can assign this to him.

**Comment by SurendarSingh** [comment]
Ok I will go it
Thanks

**Comment by Sri-vishnu-r1431** [comment]
Hey  manager who's is handling this issue I created it kindly assign it to me

**Comment by ashutoshkrris** [comment]
Fair enough, @Sri-vishnu-r1431 
@SurendarSingh, Since @Sri-vishnu-r1431 created the issue, I am assigning it to him

**Comment by Sri-vishnu-r1431** [comment]
Thanks manager

**Comment by SurendarSingh** [comment]
@ashutoshkrris Ok no problem, But I was half completed on it 
Can you create another issue for me?

**Comment by ashutoshkrris** [comment]
Apologies for that @SurendarSingh 
You can create a separate issue for yourself, but we don't accept same issue again. So, try to be unique with that!

**Comment by SurendarSingh** [comment]
Can i create my own issue? I don't know about that, Will the PR be considered for hacktoberfest 2021?

**Comment by ashutoshkrris** [comment]
Of course, @SurendarSingh 
It will be considered for Hacktoberfest.
I'll add the required labels on the issue and the corresponding PR. So, don't worry about that.

**Comment by Sri-vishnu-r1431** [comment]
Thanks manager and @SurendarSingh for understanding
